### PR TITLE
Use Drupal 10.0.0-beta2 release

### LINKED ISSUE #8: Use Drupal 10
Use Drupal 10 instead of Drupal 9.5.

They will be released roughly at the same time in December.
But as this is future and Drupal 10 is gonna be with Symfony 6 and better compatible with latest PHP versions.

### PR DESCRIPTION
**Pull request by back-2-95**
- Use Drupal 10
- [Drupal 10 will be released 14th of December](https://www.drupal.org/about/core/blog/drupal-10-will-be-released-december-14-2022)
- Drupal 10 is based on Symfony 6
- Drupal 9 is still installable with env `DRUPAL_VERSION: 9.5.0-beta2` when building image

Wil resolve #8

### CODE REVIEW

**Comment by back-2-95** [comment]
Note, when testing this when you already have a setup:

```
docker compose down -v
docker compose build --no-cache
docker compose up -d
```

**Comment by back-2-95** [comment]
9.5 beta had a lot of deprecation warnings while install process. 10 beta does not have any.

**Review by dunglas — APPROVED** [review]
Drupal isn't installable because it's an env var and not a build arg. But it's fine because users can just edit the Docker file if needed.

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
